theme: jekyll-theme-minimal
title: Your Name - Personal Website
description: A modern personal website showcasing my work and skills
show_downloads: false
google_analytics: # Add your Google Analytics tracking ID here if needed

# Social media links (optional)
github_username: yourusername
linkedin_username: yourlinkedin
twitter_username: yourtwitter

# SEO settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
